## EXTRAEMOS LOS DATOS DE LA API DE TMBD

In [2]:
import requests
import pandas as pd
import numpy as np
import json

### `Extraemos los datos acerca de las series:`

In [31]:
#Primero un ejemplo del acceso a una página para visualizar que tipo de datos tenemos
url = "https://api.themoviedb.org/3/discover/tv?include_adult=false&include_null_first_air_dates=false&language=en-US&page=1&sort_by=popularity.desc"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YTRjNWU0MGNlZWM2NTMwZjBhZmNkZjVmNjMwOGYyOSIsInN1YiI6IjYzZjYwYzY5OGMyMmMwMDBjZTNlNjMxMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.4k-HhqE--f_0tsWbbX2iaMeFAgyAOVSPynKbQ7rntJM"
}

r = requests.get(url, headers=headers)
r.json()

{'page': 1,
 'results': [{'backdrop_path': '/3n2TjKw3HrwDqgVgcynvantOfS3.jpg',
   'first_air_date': '2023-01-04',
   'genre_ids': [18, 10751],
   'id': 215103,
   'name': 'Teri Meri Doriyaann',
   'origin_country': ['IN'],
   'original_language': 'hi',
   'original_name': 'तेरी मेरी डोरियाँ',
   'overview': 'It’s hate at first sight for Sahiba and Angad! But destined to be together, their lives get intertwined by a marriage alliance, and a love-hate story ensues.',
   'popularity': 3113.712,
   'poster_path': '/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg',
   'vote_average': 7.2,
   'vote_count': 110},
  {'backdrop_path': '/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg',
   'first_air_date': '1952-12-26',
   'genre_ids': [10763],
   'id': 94722,
   'name': 'Tagesschau',
   'origin_country': ['DE'],
   'original_language': 'de',
   'original_name': 'Tagesschau',
   'overview': 'German daily news program, the oldest still existing program on German television.',
   'popularity': 3058.24,
   'poster_path': '/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg',
   'vote_average': 7.5,
   'vote_count': 145},
  {'backdrop_path': '/gMDRoKAN4b4oPgkOcBoV4RW0LsD.jpg',
   'first_air_date': '2022-05-02',
   'genre_ids': [18],
   'id': 216289,
   'name': 'Pyar Ka Pehla Naam: Radha Mohan',
   'origin_country': ['IN'],
   'original_language': 'hi',
   'original_name': 'Pyar Ka Pehla Naam: Radha Mohan',
   'overview': 'In modern-day Vrindavan, Mohan, a charming flute player, loses his spark post a tragedy. Radha, who admires him since her childhood days, decides to remind him of his true love, Lord Krishna.',
   'popularity': 2982.262,
   'poster_path': '/cGUF4aT3GCmCy3f84KKIpWS3kty.jpg',
   'vote_average': 6,
   'vote_count': 18},
  {'backdrop_path': '/1Xm0WqoT0DjZm5JdG2V6YFabrOz.jpg',
   'first_air_date': '2023-02-13',
   'genre_ids': [10759, 35, 18],
   'id': 215803,
   'name': 'Batang Quiapo',
   'origin_country': ['PH'],
   'original_language': 'tl',
   'original_name': 'Quiapo Kid',
   'overview': 'A young man rises to be one of the biggest outlaws in the neighborhood while he navigates his way in life to survive in Quiapo. Hoping to earn the affection of his parents, his feat draws him closer to the truth about his identity.',
   'popularity': 2940.786,
   'poster_path': '/9McqS8mgMf5NJCAKZIY6J1oOl8y.jpg',
   'vote_average': 7.1,
   'vote_count': 98},
  {'backdrop_path': '/9TXcHOeCsM8W3ZKKIKjdYUsRSeq.jpg',
   'first_air_date': '2017-07-17',
   'genre_ids': [80, 18],
   'id': 72879,
   'name': 'Tomorrow is Ours',
   'origin_country': ['FR'],
   'original_language': 'fr',
   'original_name': 'Demain nous appartient',
   'overview': 'The story revolves around the people of Sète, France. Their lives are punctuated by family rivalries, romance and scenes from daily life, but also by plots involving police investigations, secrets and betrayals.',
   'popularity': 2576.27,
   'poster_path': '/3uU5uJzOX7xe7mn7YKpBM9oiEZO.jpg',
   'vote_average': 6.6,
   'vote_count': 38},
  {'backdrop_path': '/yJEFbFax9fb8ePB0rK9UIQoXMG4.jpg',
   'first_air_date': '2023-04-17',
   'genre_ids': [18],
   'id': 222100,
   'name': 'Meant To Be',
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': 'Meant To Be',
   'overview': 'The work depicts the lives of two women, Lee Hae In, and Kang Se Na, who fell into different fates as children.',
   'popularity': 2380.38,
   'poster_path': '/xdzSO56WueBMW45QHWemV3D6mzJ.jpg',
   'vote_average': 7.1,
   'vote_count': 101},
  {'backdrop_path': '/zDUZKdCMESNbylWGybN4FMaUckG.jpg',
   'first_air_date': '2022-11-28',
   'genre_ids': [18],
   'id': 215315,
   'name': 'Rabb Se Hai Dua',
   'origin_country': ['IN'],
   'original_language': 'hi',
   'original_name': 'रब्ब से है दुआ',
   'overview': 'Dua and her husband are a perfect married couple in the eyes of their family. However, Dua’s life turns upside down when her husband seeks her permission to marry another woman.',
   'popularity': 2969.974,
   'poster_path': '/6ikbefd7VeopbBuGgioYMNU5bQj.jpg',
   'vote_average': 6.7,
   'vote_count': 89},
  {'backdrop_path': '/ohJTnu93hJ0Uonl86Wn3mOSlWXN.jpg',
   'first_air_date': '2017-02-06',
   'genre_ids': [10751, 35, 18],
   'id': 91759,
   'name': 'Come Home Love: Lo and Behold',
   'origin_country': ['HK'],
   'original_language': 'cn',
   'original_name': '愛·回家之開心速遞',
   'overview': "Hung Sue Gan starting from the bottom, established his own logistics company, which is now running smoothly. His only concern now are his three daughters. His eldest daughter has immigrated overseas. His second daughter Hung Yeuk Shui has reached the marriageable age, but has no hopes for marriage anytime soon. She is constantly bickering with her younger sister Hung Sum Yue, who is an honour student, over trivial matters, causing their father to not know whether to laugh or cry. Hung Sue Yan, Hung Sue Gan's brother, moves in with the family, temporarily ending his life as a nomadic photographer. He joins Hung Yeuk Shui's company and encounters Ko Pak Fei, the director of an online shop. The two appear to be former lovers, making for lots of laughter. Since Hung Sue Yan moved in, a series of strange events have occurred in the family. Upon investigation, the source is traced to Lung Ging Fung, a promising young man who is the son of department store mogul Lung Gam Wai.",
   'popularity': 2225.41,
   'poster_path': '/lgD4j9gUGmMckZpWWRJjorWqGVT.jpg',
   'vote_average': 4.5,
   'vote_count': 21},
  {'backdrop_path': '/2N4LXvTkUwPRkbvyzdmzvtnCHgR.jpg',
   'first_air_date': '2023-07-25',
   'genre_ids': [],
   'id': 225660,
   'name': 'Pira-Pirasong Paraiso',
   'origin_country': ['PH'],
   'original_language': 'tl',
   'original_name': 'Pira-Pirasong Paraiso',
   'overview': 'A con artist takes on the job of pretending to be one of the long-lost sisters of a young and rich woman. As she navigates a world of cunning and lies, she learns about right and wrong, love and family, and spectacular truths about herself.',
   'popularity': 2254.435,
   'poster_path': '/gELcO56G9EsUj6LSjaDq8VvI8De.jpg',
   'vote_average': 7.4,
   'vote_count': 16},
  {'backdrop_path': '/1Vj73YrMj4OLBppgZdWXoGZlsGI.jpg',
   'first_air_date': '2022-12-05',
   'genre_ids': [18, 10751, 10766],
   'id': 215902,
   'name': 'Katha Ankahee',
   'origin_country': ['IN'],
   'original_language': 'hi',
   'original_name': 'कथा अनकही',
   'overview': "Katha, a single parent, is in need of funds for her son's medical treatment. She comes across Viaan, who offers help but his conditions put her in an awkward situation.",
   'popularity': 2893.199,
   'poster_path': '/uhXU0SMPMlemKGHmwbldM60qqmW.jpg',
   'vote_average': 7.6,
   'vote_count': 104},
  {'backdrop_path': '/i4n8ZKmCUaxcGMkPhm12selZiff.jpg',
   'first_air_date': '2023-06-12',
   'genre_ids': [18, 10766],
   'id': 226411,
   'name': 'Revenge is mine',
   'origin_country': ['ES'],
   'original_language': 'es',
   'original_name': 'Mía es la venganza',
   'overview': '',
   'popularity': 2099.253,
   'poster_path': '/wysp5AcY9JpLjje5NunKYw7Mrtc.jpg',
   'vote_average': 7.3,
   'vote_count': 56},
  {'backdrop_path': '/5MkBAawsj7O9zitVtzMXagyrIBw.jpg',
   'first_air_date': '2023-01-30',
   'genre_ids': [18, 10766],
   'id': 217216,
   'name': 'Flor Sem Tempo',
   'origin_country': ['PT'],
   'original_language': 'pt',
   'original_name': 'Flor Sem Tempo',
   'overview': '',
   'popularity': 2770.099,
   'poster_path': '/bclnfDXvx7UydFSk83B258vRRvI.jpg',
   'vote_average': 7.3,
   'vote_count': 42},
  {'backdrop_path': '/kdF7ZTktLHVVhAhI90uuzqlZqJI.jpg',
   'first_air_date': '2023-06-06',
   'genre_ids': [18],
   'id': 228093,
   'name': 'Titlie',
   'origin_country': ['IN'],
   'original_language': 'hi',
   'original_name': 'Titlie',
   'overview': 'Obsessed by the notion of fairy tale love , Titlie marries her beau Garv . Soon , the picture - perfect romance turns abusive , forcing her to wrestle with reality .',
   'popularity': 2069.281,
   'poster_path': '/5kZi1LCFugNAeDCWOF3ornGNm2W.jpg',
   'vote_average': 7.9,
   'vote_count': 85},
  {'backdrop_path': '/5e1MxLWTJh6n4qtYz0vlevOK6qW.jpg',
   'first_air_date': '2023-07-03',
   'genre_ids': [18, 10766],
   'id': 229932,
   'name': 'Pyaar Ka Pehla Adhyaya  - Shiv Shakti',
   'origin_country': ['IN'],
   'original_language': 'hi',
   'original_name': 'Pyaar Ka Pehla Adhyaya  - Shiv Shakti',
   'overview': 'Shiv has a rewarding career as a doctor, but his personal life is in tatters. Shakti, an orphan, is a nurturer by nature. Will Shakti heal a broken Shiv?',
   'popularity': 1974.066,
   'poster_path': '/jHK9bCDefHq43cHvMVUM7SLumYF.jpg',
   'vote_average': 8.1,
   'vote_count': 52},
  {'backdrop_path': '/yYNa1nqvNK94xZz3eKyfvZdAvPi.jpg',
   'first_air_date': '2020-11-02',
   'genre_ids': [10766],
   'id': 112470,
   'name': 'Here it all begins',
   'origin_country': ['FR'],
   'original_language': 'fr',
   'original_name': 'Ici tout commence',
   'overview': '',
   'popularity': 1918.512,
   'poster_path': '/60cqjI590JKXCAABqCStVmSBGET.jpg',
   'vote_average': 7.1,
   'vote_count': 27},
  {'backdrop_path': '/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg',
   'first_air_date': '2023-05-08',
   'genre_ids': [18, 80, 10766],
   'id': 209265,
   'name': 'Land of Desire',
   'origin_country': ['BR'],
   'original_language': 'pt',
   'original_name': 'Terra e Paixão',
   'overview': 'The saga of a woman, guided by the power of love and moved by the desire for justice, who crosses paths with a family divided by ambition and many secrets.',
   'popularity': 1947.547,
   'poster_path': '/5kCMJ0vVzN9PsoamKctNnUz68Q2.jpg',
   'vote_average': 6.6,
   'vote_count': 116},
  {'backdrop_path': '/oevegczrAOpdnzL96KWtspNfzRw.jpg',
   'first_air_date': '2023-08-21',
   'genre_ids': [],
   'id': 233015,
   'name': 'Baatein Kuch Ankahee Si',
   'origin_country': ['IN'],
   'original_language': 'hi',
   'original_name': 'Baatein Kuch Ankahee Si',
   'overview': "The series revolves around the lives of three sisters, with the eldest sister taking on the role of the family's breadwinner. Despite her achievements, she faces judgment for remaining unmarried at the age of 35. On the other hand, the protagonist maintains her belief that someday she will meet her Mr. Right.",
   'popularity': 1812.194,
   'poster_path': None,
   'vote_average': 8,
   'vote_count': 2},
  {'backdrop_path': '/69Jblm3seQgiPuPQMrJqg9Nxhaz.jpg',
   'first_air_date': '2011-01-10',
   'genre_ids': [10763, 10767],
   'id': 101463,
   'name': 'Al rojo vivo',
   'origin_country': ['ES'],
   'original_language': 'es',
   'original_name': 'Al rojo vivo',
   'overview': '',
   'popularity': 2378.864,
   'poster_path': '/ag6PmoBxkF2s1uY3An618NCEt3g.jpg',
   'vote_average': 2.9,
   'vote_count': 12},
  {'backdrop_path': '/1stoC4UstDtmST8x8VATtf08KfL.jpg',
   'first_air_date': '2005-10-13',
   'genre_ids': [10766],
   'id': 206559,
   'name': 'Binnelanders',
   'origin_country': ['ZA'],
   'original_language': 'af',
   'original_name': 'Binnelanders',
   'overview': 'A South African Afrikaans soap opera. It is set in and around the fictional private hospital, Binneland Kliniek, in Pretoria, and the storyline follows the trials, trauma and tribulations of the staff and patients of the hospital.',
   'popularity': 2059.117,
   'poster_path': '/v9nGSRx5lFz6KEgfmgHJMSgaARC.jpg',
   'vote_average': 6.8,
   'vote_count': 5},
  {'backdrop_path': '/jKbqVjCOOL2P8cP1VNxbC2h31Re.jpg',
   'first_air_date': '2019-01-11',
   'genre_ids': [35, 18],
   'id': 81356,
   'name': 'Sex Education',
   'origin_country': ['GB'],
   'original_language': 'en',
   'original_name': 'Sex Education',
   'overview': 'Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.',
   'popularity': 1550.808,
   'poster_path': '/zn6VNUOHGWKvSGRL6KiMtAe9ELy.jpg',
   'vote_average': 8.3,
   'vote_count': 6590}],
 'total_pages': 7812,
 'total_results': 156238}

In [32]:
r.json().keys()
#solo nos interesa acceder a los resultados

dict_keys(['page', 'results', 'total_pages', 'total_results'])

In [33]:
r.json()['results']

[{'backdrop_path': '/3n2TjKw3HrwDqgVgcynvantOfS3.jpg',
  'first_air_date': '2023-01-04',
  'genre_ids': [18, 10751],
  'id': 215103,
  'name': 'Teri Meri Doriyaann',
  'origin_country': ['IN'],
  'original_language': 'hi',
  'original_name': 'तेरी मेरी डोरियाँ',
  'overview': 'It’s hate at first sight for Sahiba and Angad! But destined to be together, their lives get intertwined by a marriage alliance, and a love-hate story ensues.',
  'popularity': 3113.712,
  'poster_path': '/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg',
  'vote_average': 7.2,
  'vote_count': 110},
 {'backdrop_path': '/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg',
  'first_air_date': '1952-12-26',
  'genre_ids': [10763],
  'id': 94722,
  'name': 'Tagesschau',
  'origin_country': ['DE'],
  'original_language': 'de',
  'original_name': 'Tagesschau',
  'overview': 'German daily news program, the oldest still existing program on German television.',
  'popularity': 3058.24,
  'poster_path': '/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg',
  'vote_average': 7.5,
  'vote_count': 145},
 {'backdrop_path': '/gMDRoKAN4b4oPgkOcBoV4RW0LsD.jpg',
  'first_air_date': '2022-05-02',
  'genre_ids': [18],
  'id': 216289,
  'name': 'Pyar Ka Pehla Naam: Radha Mohan',
  'origin_country': ['IN'],
  'original_language': 'hi',
  'original_name': 'Pyar Ka Pehla Naam: Radha Mohan',
  'overview': 'In modern-day Vrindavan, Mohan, a charming flute player, loses his spark post a tragedy. Radha, who admires him since her childhood days, decides to remind him of his true love, Lord Krishna.',
  'popularity': 2982.262,
  'poster_path': '/cGUF4aT3GCmCy3f84KKIpWS3kty.jpg',
  'vote_average': 6,
  'vote_count': 18},
 {'backdrop_path': '/1Xm0WqoT0DjZm5JdG2V6YFabrOz.jpg',
  'first_air_date': '2023-02-13',
  'genre_ids': [10759, 35, 18],
  'id': 215803,
  'name': 'Batang Quiapo',
  'origin_country': ['PH'],
  'original_language': 'tl',
  'original_name': 'Quiapo Kid',
  'overview': 'A young man rises to be one of the biggest outlaws in the neighborhood while he navigates his way in life to survive in Quiapo. Hoping to earn the affection of his parents, his feat draws him closer to the truth about his identity.',
  'popularity': 2940.786,
  'poster_path': '/9McqS8mgMf5NJCAKZIY6J1oOl8y.jpg',
  'vote_average': 7.1,
  'vote_count': 98},
 {'backdrop_path': '/9TXcHOeCsM8W3ZKKIKjdYUsRSeq.jpg',
  'first_air_date': '2017-07-17',
  'genre_ids': [80, 18],
  'id': 72879,
  'name': 'Tomorrow is Ours',
  'origin_country': ['FR'],
  'original_language': 'fr',
  'original_name': 'Demain nous appartient',
  'overview': 'The story revolves around the people of Sète, France. Their lives are punctuated by family rivalries, romance and scenes from daily life, but also by plots involving police investigations, secrets and betrayals.',
  'popularity': 2576.27,
  'poster_path': '/3uU5uJzOX7xe7mn7YKpBM9oiEZO.jpg',
  'vote_average': 6.6,
  'vote_count': 38},
 {'backdrop_path': '/yJEFbFax9fb8ePB0rK9UIQoXMG4.jpg',
  'first_air_date': '2023-04-17',
  'genre_ids': [18],
  'id': 222100,
  'name': 'Meant To Be',
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': 'Meant To Be',
  'overview': 'The work depicts the lives of two women, Lee Hae In, and Kang Se Na, who fell into different fates as children.',
  'popularity': 2380.38,
  'poster_path': '/xdzSO56WueBMW45QHWemV3D6mzJ.jpg',
  'vote_average': 7.1,
  'vote_count': 101},
 {'backdrop_path': '/zDUZKdCMESNbylWGybN4FMaUckG.jpg',
  'first_air_date': '2022-11-28',
  'genre_ids': [18],
  'id': 215315,
  'name': 'Rabb Se Hai Dua',
  'origin_country': ['IN'],
  'original_language': 'hi',
  'original_name': 'रब्ब से है दुआ',
  'overview': 'Dua and her husband are a perfect married couple in the eyes of their family. However, Dua’s life turns upside down when her husband seeks her permission to marry another woman.',
  'popularity': 2969.974,
  'poster_path': '/6ikbefd7VeopbBuGgioYMNU5bQj.jpg',
  'vote_average': 6.7,
  'vote_count': 89},
 {'backdrop_path': '/ohJTnu93hJ0Uonl86Wn3mOSlWXN.jpg',
  'first_air_date': '2017-02-06',
  'genre_ids': [10751, 35, 18],
  'id': 91759,
  'name': 'Come Home Love: Lo and Behold',
  'origin_country': ['HK'],
  'original_language': 'cn',
  'original_name': '愛·回家之開心速遞',
  'overview': "Hung Sue Gan starting from the bottom, established his own logistics company, which is now running smoothly. His only concern now are his three daughters. His eldest daughter has immigrated overseas. His second daughter Hung Yeuk Shui has reached the marriageable age, but has no hopes for marriage anytime soon. She is constantly bickering with her younger sister Hung Sum Yue, who is an honour student, over trivial matters, causing their father to not know whether to laugh or cry. Hung Sue Yan, Hung Sue Gan's brother, moves in with the family, temporarily ending his life as a nomadic photographer. He joins Hung Yeuk Shui's company and encounters Ko Pak Fei, the director of an online shop. The two appear to be former lovers, making for lots of laughter. Since Hung Sue Yan moved in, a series of strange events have occurred in the family. Upon investigation, the source is traced to Lung Ging Fung, a promising young man who is the son of department store mogul Lung Gam Wai.",
  'popularity': 2225.41,
  'poster_path': '/lgD4j9gUGmMckZpWWRJjorWqGVT.jpg',
  'vote_average': 4.5,
  'vote_count': 21},
 {'backdrop_path': '/2N4LXvTkUwPRkbvyzdmzvtnCHgR.jpg',
  'first_air_date': '2023-07-25',
  'genre_ids': [],
  'id': 225660,
  'name': 'Pira-Pirasong Paraiso',
  'origin_country': ['PH'],
  'original_language': 'tl',
  'original_name': 'Pira-Pirasong Paraiso',
  'overview': 'A con artist takes on the job of pretending to be one of the long-lost sisters of a young and rich woman. As she navigates a world of cunning and lies, she learns about right and wrong, love and family, and spectacular truths about herself.',
  'popularity': 2254.435,
  'poster_path': '/gELcO56G9EsUj6LSjaDq8VvI8De.jpg',
  'vote_average': 7.4,
  'vote_count': 16},
 {'backdrop_path': '/1Vj73YrMj4OLBppgZdWXoGZlsGI.jpg',
  'first_air_date': '2022-12-05',
  'genre_ids': [18, 10751, 10766],
  'id': 215902,
  'name': 'Katha Ankahee',
  'origin_country': ['IN'],
  'original_language': 'hi',
  'original_name': 'कथा अनकही',
  'overview': "Katha, a single parent, is in need of funds for her son's medical treatment. She comes across Viaan, who offers help but his conditions put her in an awkward situation.",
  'popularity': 2893.199,
  'poster_path': '/uhXU0SMPMlemKGHmwbldM60qqmW.jpg',
  'vote_average': 7.6,
  'vote_count': 104},
 {'backdrop_path': '/i4n8ZKmCUaxcGMkPhm12selZiff.jpg',
  'first_air_date': '2023-06-12',
  'genre_ids': [18, 10766],
  'id': 226411,
  'name': 'Revenge is mine',
  'origin_country': ['ES'],
  'original_language': 'es',
  'original_name': 'Mía es la venganza',
  'overview': '',
  'popularity': 2099.253,
  'poster_path': '/wysp5AcY9JpLjje5NunKYw7Mrtc.jpg',
  'vote_average': 7.3,
  'vote_count': 56},
 {'backdrop_path': '/5MkBAawsj7O9zitVtzMXagyrIBw.jpg',
  'first_air_date': '2023-01-30',
  'genre_ids': [18, 10766],
  'id': 217216,
  'name': 'Flor Sem Tempo',
  'origin_country': ['PT'],
  'original_language': 'pt',
  'original_name': 'Flor Sem Tempo',
  'overview': '',
  'popularity': 2770.099,
  'poster_path': '/bclnfDXvx7UydFSk83B258vRRvI.jpg',
  'vote_average': 7.3,
  'vote_count': 42},
 {'backdrop_path': '/kdF7ZTktLHVVhAhI90uuzqlZqJI.jpg',
  'first_air_date': '2023-06-06',
  'genre_ids': [18],
  'id': 228093,
  'name': 'Titlie',
  'origin_country': ['IN'],
  'original_language': 'hi',
  'original_name': 'Titlie',
  'overview': 'Obsessed by the notion of fairy tale love , Titlie marries her beau Garv . Soon , the picture - perfect romance turns abusive , forcing her to wrestle with reality .',
  'popularity': 2069.281,
  'poster_path': '/5kZi1LCFugNAeDCWOF3ornGNm2W.jpg',
  'vote_average': 7.9,
  'vote_count': 85},
 {'backdrop_path': '/5e1MxLWTJh6n4qtYz0vlevOK6qW.jpg',
  'first_air_date': '2023-07-03',
  'genre_ids': [18, 10766],
  'id': 229932,
  'name': 'Pyaar Ka Pehla Adhyaya  - Shiv Shakti',
  'origin_country': ['IN'],
  'original_language': 'hi',
  'original_name': 'Pyaar Ka Pehla Adhyaya  - Shiv Shakti',
  'overview': 'Shiv has a rewarding career as a doctor, but his personal life is in tatters. Shakti, an orphan, is a nurturer by nature. Will Shakti heal a broken Shiv?',
  'popularity': 1974.066,
  'poster_path': '/jHK9bCDefHq43cHvMVUM7SLumYF.jpg',
  'vote_average': 8.1,
  'vote_count': 52},
 {'backdrop_path': '/yYNa1nqvNK94xZz3eKyfvZdAvPi.jpg',
  'first_air_date': '2020-11-02',
  'genre_ids': [10766],
  'id': 112470,
  'name': 'Here it all begins',
  'origin_country': ['FR'],
  'original_language': 'fr',
  'original_name': 'Ici tout commence',
  'overview': '',
  'popularity': 1918.512,
  'poster_path': '/60cqjI590JKXCAABqCStVmSBGET.jpg',
  'vote_average': 7.1,
  'vote_count': 27},
 {'backdrop_path': '/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg',
  'first_air_date': '2023-05-08',
  'genre_ids': [18, 80, 10766],
  'id': 209265,
  'name': 'Land of Desire',
  'origin_country': ['BR'],
  'original_language': 'pt',
  'original_name': 'Terra e Paixão',
  'overview': 'The saga of a woman, guided by the power of love and moved by the desire for justice, who crosses paths with a family divided by ambition and many secrets.',
  'popularity': 1947.547,
  'poster_path': '/5kCMJ0vVzN9PsoamKctNnUz68Q2.jpg',
  'vote_average': 6.6,
  'vote_count': 116},
 {'backdrop_path': '/oevegczrAOpdnzL96KWtspNfzRw.jpg',
  'first_air_date': '2023-08-21',
  'genre_ids': [],
  'id': 233015,
  'name': 'Baatein Kuch Ankahee Si',
  'origin_country': ['IN'],
  'original_language': 'hi',
  'original_name': 'Baatein Kuch Ankahee Si',
  'overview': "The series revolves around the lives of three sisters, with the eldest sister taking on the role of the family's breadwinner. Despite her achievements, she faces judgment for remaining unmarried at the age of 35. On the other hand, the protagonist maintains her belief that someday she will meet her Mr. Right.",
  'popularity': 1812.194,
  'poster_path': None,
  'vote_average': 8,
  'vote_count': 2},
 {'backdrop_path': '/69Jblm3seQgiPuPQMrJqg9Nxhaz.jpg',
  'first_air_date': '2011-01-10',
  'genre_ids': [10763, 10767],
  'id': 101463,
  'name': 'Al rojo vivo',
  'origin_country': ['ES'],
  'original_language': 'es',
  'original_name': 'Al rojo vivo',
  'overview': '',
  'popularity': 2378.864,
  'poster_path': '/ag6PmoBxkF2s1uY3An618NCEt3g.jpg',
  'vote_average': 2.9,
  'vote_count': 12},
 {'backdrop_path': '/1stoC4UstDtmST8x8VATtf08KfL.jpg',
  'first_air_date': '2005-10-13',
  'genre_ids': [10766],
  'id': 206559,
  'name': 'Binnelanders',
  'origin_country': ['ZA'],
  'original_language': 'af',
  'original_name': 'Binnelanders',
  'overview': 'A South African Afrikaans soap opera. It is set in and around the fictional private hospital, Binneland Kliniek, in Pretoria, and the storyline follows the trials, trauma and tribulations of the staff and patients of the hospital.',
  'popularity': 2059.117,
  'poster_path': '/v9nGSRx5lFz6KEgfmgHJMSgaARC.jpg',
  'vote_average': 6.8,
  'vote_count': 5},
 {'backdrop_path': '/jKbqVjCOOL2P8cP1VNxbC2h31Re.jpg',
  'first_air_date': '2019-01-11',
  'genre_ids': [35, 18],
  'id': 81356,
  'name': 'Sex Education',
  'origin_country': ['GB'],
  'original_language': 'en',
  'original_name': 'Sex Education',
  'overview': 'Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.',
  'popularity': 1550.808,
  'poster_path': '/zn6VNUOHGWKvSGRL6KiMtAe9ELy.jpg',
  'vote_average': 8.3,
  'vote_count': 6590}]

In [34]:
len(r.json()['results'])
#Con esto vemos cuantos resultados hay por página

20

In [39]:
r.json()['results'][19]

{'backdrop_path': '/jKbqVjCOOL2P8cP1VNxbC2h31Re.jpg',
 'first_air_date': '2019-01-11',
 'genre_ids': [35, 18],
 'id': 81356,
 'name': 'Sex Education',
 'origin_country': ['GB'],
 'original_language': 'en',
 'original_name': 'Sex Education',
 'overview': 'Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.',
 'popularity': 1550.808,
 'poster_path': '/zn6VNUOHGWKvSGRL6KiMtAe9ELy.jpg',
 'vote_average': 8.3,
 'vote_count': 6590}

In [36]:
r.json()['results'][0]['name']

'Teri Meri Doriyaann'

In [3]:
#Ahora vamos a crear un bucle while para obtener la información de las 100 primeras páginas
i = 1
serie_id = []
name = []
genre_id =[]
origin_country = []
original_language =[]
popularity = []
vote_average = []
vote_count = []

while i < 100:
  url = "https://api.themoviedb.org/3/discover/tv?include_adult=false&include_null_first_air_dates=false&language=en-US&page={}&sort_by=popularity.desc".format(i)
  headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YTRjNWU0MGNlZWM2NTMwZjBhZmNkZjVmNjMwOGYyOSIsInN1YiI6IjYzZjYwYzY5OGMyMmMwMDBjZTNlNjMxMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.4k-HhqE--f_0tsWbbX2iaMeFAgyAOVSPynKbQ7rntJM"
    }
  response = requests.get(url, headers=headers)
  j = response.json()
  
  for z in range(20):
    serie_id.append(j['results'][z]['id'])
    name.append(j['results'][z]['name'])
    genre_id.append(j['results'][z]['genre_ids'])
    origin_country.append(j['results'][z]['origin_country'])
    popularity.append(j['results'][z]['popularity'])
    vote_average.append(j['results'][z]['vote_average'])
    vote_count.append(j['results'][z]['vote_count'])
  
  i += 1

In [4]:
data = {
    'serie_id': serie_id,
    'name': name,
    'genre_id': genre_id,
    'origin_country': origin_country,
    'popularity': popularity,
    'vote_average': vote_average,
    'vote_count': vote_count
}

series = pd.DataFrame(data)
series

,serie_id,name,genre_id,origin_country,popularity,vote_average,vote_count
0,94722,Tagesschau,[10763],[DE],3183.847,7.5,145
1,215103,Teri Meri Doriyaann,"[18, 10751]",[IN],3103.841,7.2,110
2,215803,Batang Quiapo,"[10759, 35, 18]",[PH],3072.452,7.0,99
3,215315,Rabb Se Hai Dua,[18],[IN],3061.452,6.7,90
4,215902,Katha Ankahee,"[18, 10751, 10766]",[IN],2986.341,7.5,106
...,...,...,...,...,...,...,...
1975,214915,Office Romance Recipe,"[35, 18]",[KR],48.643,0.0,0
1976,36062,Best Friends,"[35, 18, 10766]",[NL],48.639,4.0,4
1977,104288,The Best of WWE,[],[],48.612,9.7,3
1978,2181,Route 66,[18],[US],48.603,6.3,13
1979,205442,La mujer del diablo,[18],[MX],48.599,7.6,207

In [12]:
# Y guardamos el df obtenido para posteriormente trabajar con el
series.to_csv("../Data/series.csv")

Sacamos información sobre los géneros y los actores

In [5]:
#Llamamos a la API para obtener una tabla de qué género corresponde con cada ID

url = "https://api.themoviedb.org/3/genre/tv/list?language=en"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YTRjNWU0MGNlZWM2NTMwZjBhZmNkZjVmNjMwOGYyOSIsInN1YiI6IjYzZjYwYzY5OGMyMmMwMDBjZTNlNjMxMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.4k-HhqE--f_0tsWbbX2iaMeFAgyAOVSPynKbQ7rntJM"
}

response = requests.get(url, headers=headers)

j= response.json()
j

{'genres': [{'id': 10759, 'name': 'Action & Adventure'},
  {'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 80, 'name': 'Crime'},
  {'id': 99, 'name': 'Documentary'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10751, 'name': 'Family'},
  {'id': 10762, 'name': 'Kids'},
  {'id': 9648, 'name': 'Mystery'},
  {'id': 10763, 'name': 'News'},
  {'id': 10764, 'name': 'Reality'},
  {'id': 10765, 'name': 'Sci-Fi & Fantasy'},
  {'id': 10766, 'name': 'Soap'},
  {'id': 10767, 'name': 'Talk'},
  {'id': 10768, 'name': 'War & Politics'},
  {'id': 37, 'name': 'Western'}]}

In [51]:
j['genres'][0]

{'id': 10759, 'name': 'Action & Adventure'}

In [6]:
id = []
genre = []

for i in range(len(j['genres'])):
    id.append(j['genres'][i]['id'])
    genre.append(j['genres'][i]['name'])

In [13]:
#Creamos el df con los géneros

data = {'id': id, 'genre': genre}

series_genre_df = pd.DataFrame(data).sort_values(by= 'id', ascending= True)
series_genre_df.reset_index(inplace=True, drop= True)
series_genre_df

       id               genre
0      16           Animation
1      18               Drama
2      35              Comedy
3      37             Western
4      80               Crime
5      99         Documentary
6    9648             Mystery
7   10751              Family
8   10759  Action & Adventure
9   10762                Kids
10  10763                News
11  10764             Reality
12  10765    Sci-Fi & Fantasy
13  10766                Soap
14  10767                Talk
15  10768      War & Politics

In [14]:
# Y lo guardamos como otro csv para posteriormente trabajar con él

series_genre_df.to_csv("../Data/series_genre.csv")

--------

### `Extraemos los datos acerca de las películas:`

In [15]:
i = 1
film_id = []
title = []
genre_id =[]
original_language =[]
release_date = []
popularity = []
vote_average = []
vote_count = []

while i < 100:

    url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page={}&sort_by=popularity.desc".format(i)
    headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YTRjNWU0MGNlZWM2NTMwZjBhZmNkZjVmNjMwOGYyOSIsInN1YiI6IjYzZjYwYzY5OGMyMmMwMDBjZTNlNjMxMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.4k-HhqE--f_0tsWbbX2iaMeFAgyAOVSPynKbQ7rntJM"
    }

    response = requests.get(url, headers=headers)
    j = response.json()

    for z in range(20):
        film_id.append(j['results'][z]['id'])
        title.append(j['results'][z]['title'])
        original_language.append(j['results'][z]['original_language'])
        genre_id.append(j['results'][z]['genre_ids'])
        popularity.append(j['results'][z]['popularity'])
        vote_average.append(j['results'][z]['vote_average'])
        vote_count.append(j['results'][z]['vote_count'])
        release_date.append(j['results'][z]['release_date'])

    i += 1

In [16]:
data = {
    'film_id': film_id,
    'title': title,
    'original_language': original_language,
    'genre_ids': genre_id,
    'release_date': release_date,
    'popularity': popularity,
    'vote_average': vote_average,
    'vote_count': vote_count
}

films = pd.DataFrame(data)
films

,film_id,title,original_language,genre_ids,release_date,popularity,vote_average,vote_count
0,565770,Blue Beetle,en,"[28, 878, 12]",2023-08-16,3180.600,7.2,910
1,762430,Retribution,en,"[28, 9648, 53, 80]",2023-08-23,1730.839,6.8,230
2,615656,Meg 2: The Trench,en,"[28, 878, 27]",2023-08-02,1363.273,7.0,1959
3,385687,Fast X,en,"[28, 80, 53]",2023-05-17,1264.755,7.3,3852
4,1008042,Talk to Me,en,"[27, 53]",2023-07-26,1207.188,7.2,876
...,...,...,...,...,...,...,...,...
1975,340382,Attack on Titan II: End of the World,ja,"[27, 878, 28, 14]",2015-09-01,34.586,6.1,290
1976,51739,The Secret World of Arrietty,ja,"[14, 16, 10751]",2010-07-16,34.580,7.6,2561
1977,630940,Jokyoshi Nikki 2 Abakareta Sei,ja,[],1996-06-13,34.577,9.3,6
1978,1954,The Butterfly Effect,en,"[878, 53]",2004-01-17,34.573,7.6,6889
1979,23202,Trick 'r Treat,en,"[27, 35]",2007-10-26,34.572,7.0,1666

In [17]:
#Guardamos nuestro df en un csv para posteriormente trabajar con él

films.to_csv('../Data/films.csv')

Sacamos también información sobre los géneros:

In [18]:
#Llamamos a la API para obtener una tabla de qué género corresponde con cada ID

url = "https://api.themoviedb.org/3/genre/movie/list?language=en"


headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YTRjNWU0MGNlZWM2NTMwZjBhZmNkZjVmNjMwOGYyOSIsInN1YiI6IjYzZjYwYzY5OGMyMmMwMDBjZTNlNjMxMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.4k-HhqE--f_0tsWbbX2iaMeFAgyAOVSPynKbQ7rntJM"
}

response = requests.get(url, headers=headers)

j= response.json()
j

{'genres': [{'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'},
  {'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 80, 'name': 'Crime'},
  {'id': 99, 'name': 'Documentary'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10751, 'name': 'Family'},
  {'id': 14, 'name': 'Fantasy'},
  {'id': 36, 'name': 'History'},
  {'id': 27, 'name': 'Horror'},
  {'id': 10402, 'name': 'Music'},
  {'id': 9648, 'name': 'Mystery'},
  {'id': 10749, 'name': 'Romance'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 10770, 'name': 'TV Movie'},
  {'id': 53, 'name': 'Thriller'},
  {'id': 10752, 'name': 'War'},
  {'id': 37, 'name': 'Western'}]}

In [57]:
j['genres'][0]

{'id': 28, 'name': 'Action'}

In [19]:
id = []
genre = []

for i in range(len(j['genres'])):
    id.append(j['genres'][i]['id'])
    genre.append(j['genres'][i]['name'])

In [20]:
#Creamos el df con los géneros

data = {'id': id, 'genre': genre}

genre_films_df = pd.DataFrame(data).sort_values(by= 'id', ascending= True)
genre_films_df.reset_index(inplace=True, drop= True)
genre_films_df

       id            genre
0      12        Adventure
1      14          Fantasy
2      16        Animation
3      18            Drama
4      27           Horror
5      28           Action
6      35           Comedy
7      36          History
8      37          Western
9      53         Thriller
10     80            Crime
11     99      Documentary
12    878  Science Fiction
13   9648          Mystery
14  10402            Music
15  10749          Romance
16  10751           Family
17  10752              War
18  10770         TV Movie

In [21]:
# Y lo guardamos

genre_films_df.to_csv('../Data/films_genre.csv')